config/routes.rb
QuantifiedSusan::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation
  has_secure_password

  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
  end

  def create
  	user = User.find_by_name(params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
	def show
		@user = User.find(params[:id])
	end

  def new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome"
      redirect_to @user
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by susan
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "quantified susan", '#', id: "logo" %>
      <nav>
      	<ul class="nav pull-right">
      		<% if signed_in? %>
      			<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuantifiedSusan</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
 <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Quantified Susan</h1>

  <h2>Do you really want to see this</h2>

  <%= link_to "yes", signin_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% if signed_in? %>
	<div>
		<h3>Profile</h3>
		<li><b>Activated:</b> May 2014</li>
		<li><b>Platform:</b> iOS & Android</li>
		<li><b>Current watch:</b> Bobby</li>
		<li><b>Watches owned:</b> Tintin, Steel, Snowy, Bobby, S4</li>
		<li><b>Kickstarter?</b> No :(</li>
	</div>

	<p>&nbsp;</p>

	<div>
		<h3>Activity</h3>
		<p><b>Avg Hours:</b> 12/weekday, 4/weekend</p>
		<%= image_tag("hours.png", size: "500x300") %>
	</div>

	<div>
		<h3>Calendar</h3>
		<p style="text-align:left">
			<b>Avg Events:</b> 6/weekday, 0/weekend
			<span style="float:right">
				<b>Busiest on:</b> Tuesday, Thursday
			</span>
		</p>
		<p style="text-align:left">
		<%= image_tag("calendar.png", size: "1000x500") %>
		</p>
	</div>

	<p>&nbsp;</p>

	<div>
		<h3>Notifications</h3>
		<p><b>Avg Notifications:</b> 88/weekday, 8/weekend</p>
		<div class="row">
			<div class="span5" align="left">
				<p><b>Notifications by Time of Day</b></p>
				<%= image_tag("notifications.png", size: "400x200") %>
			</div>
			<div class="span5 offset1" align="left">
				<p><b>Top Notifications Sources</b></p>
					<table id="t01" style="width:100%">
						<tr><th>Source</th><th>% Notifs</th></tr>
	  				<tr><td>Gmail</td><td>65%</td></tr>
	  				<tr><td>Inbox</td><td>22%</td></tr>
	  				<tr><td>Calendar</td><td>3%</td></tr>
	  				<tr><td>WhatsApp</td><td>2%</td></tr>
	  				<tr><td>Hangouts</td><td>2%</td></tr>
	  				<tr><td>Dropcam</td><td>1%</td></tr>
	  				<tr><td>Google App</td><td>1%</td></tr>
					</table>
			</div>
		</div>
	</div>

	<p>&nbsp;</p>

	<div>
		<div class="row">
			<div class="span3" align="left">
				<h3>Apps</h3>
					<table id="t01" style="width:100%">
						<tr><th>App</th><th># Launches</th></tr>
	  				<tr><td>Notifications</td><td>44</td></tr>
	  				<tr><td>Voice</td><td>20</td></tr>
	  				<tr><td>Timeline</td><td>19</td></tr>
					</table>
			</div>
			<div class="span3 offset1" align="left">
				<h3>Faces</h3>
					<table id="t01" style="width:100%">
						<tr><th>Face</th><th># Hours</th></tr>
	  				<tr><td>Mosaic</td><td>166.6</td></tr>
	  				<tr><td>TicToc</td><td>0.2</td></tr>
					</table>
			</div>
			<div class="span3 offset1" align="left">
				<h3>Pins</h3>
					<table id="t01" style="width:100%">
						<tr><th>Source</th><th># Pins</th></tr>
	  				<tr><td>Calendar</td><td>35</td></tr>
	  				<tr><td>Weather</td><td>6</td></tr>
					</table>
			</div>
		</div>
	</div>

	<p>&nbsp;</p>

	<div>
		<h3>Health</h3>
		
	</div>

<% else %>
	<p>Please sign in</p>
<% end %>